package com.violinjourney.app.feature.home.art

/** Silhouettes of the houses (grid 200 × 120) — generated by tools/home/export.js from the handoff's `SIL`. */
object HomeSilhouettes {
    val paths: Map<String, List<String>> = mapOf(
        "rent" to listOf("M40 110L40 30L160 30L160 110Z", "M56 44h14v18h-14Z", "M88 44h14v18h-14Z", "M120 44h14v18h-14Z", "M56 72h14v18h-14Z", "M88 72h14v18h-14Z", "M120 72h14v18h-14Z"),
        "wood" to listOf("M40 110L40 62L100 26L160 62L160 110Z", "M120 30h10v26h-10Z", "M90 80h20v30h-20Z", "M56 70h18v16h-18Z"),
        "flat" to listOf("M30 110L30 24L170 24L170 110Z", "M80 110L80 50L92 40L108 40L120 50L120 110Z", "M44 40h14v20h-14Z", "M142 40h14v20h-14Z", "M44 74h14v20h-14Z", "M142 74h14v20h-14Z"),
        "sea" to listOf("M30 110L30 70L90 40L150 70L150 110Z", "M160 110L163 50L175 50L178 110Z", "M162 44a7 7 0 1 0 14 0a7 7 0 1 0 -14 0Z", "M20 104h160v6h-160Z"),
        "chalet" to listOf("M20 110L20 74L100 22L180 74L180 110Z", "M60 80h80v6h-80Z", "M120 40h10v20h-10Z"),
        "mansion" to listOf("M30 110L30 56L170 56L170 110Z", "M24 56L100 22L176 56Z", "M46 64h8v46h-8Z", "M76 64h8v46h-8Z", "M106 64h8v46h-8Z", "M136 64h8v46h-8Z"),
        "villa" to listOf("M20 110L20 60L110 60L110 110Z", "M120 76h60v34h-60Z", "M120 76a30 30 0 0 1 60 0Z", "M34 72h12v24h-12Z", "M58 72h12v24h-12Z", "M82 72h12v24h-12Z"),
    )
}
