// Launcher icon «Гриф-дорога» (variant 1b of the handoff `docs/design/project/icon_app/project/Значок v2.dc.html`)
// → adaptive icon layers as vector drawables, and the 512 px icon for the stores (docs/store/icon-512.png). The geometry comes from the handoff's own generator
// `icon-v2-gen.js` (build().b): changed there, regenerate here with `node tools/icon/export.js`.
// Layers as the handoff says: sky and ground — background, the fingerboard and the head — foreground;
// monochrome (themed icons, Android 13+) — the handoff's `mono`, with the scroll's groove cut out.
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const { execFileSync } = require('child_process');

const root = path.join(__dirname, '..', '..');
const handoff = path.join(root, 'docs/design/project/icon_app/project');
const ctx = {};
vm.runInNewContext(fs.readFileSync(path.join(handoff, 'icon-v2-gen.js'), 'utf8') + '\nthis.I = build();', ctx);
const icon = ctx.I.b;

const attrs = s => Object.fromEntries([...s.matchAll(/(\w+)="([^"]*)"/g)].map(m => [m[1], m[2]]));
const elements = (s, tag) => [...s.matchAll(new RegExp(`<${tag}\\b([^>]*)>`, 'g'))].map(m => attrs(m[1]));

// Gradients of the handoff, by id.
const gradients = {};
for (const m of icon.defs.matchAll(/<(linear|radial)Gradient\b([^>]*)>(.*?)<\/\1Gradient>/g)) {
  gradients[attrs(m[2]).id] = { type: m[1], ...attrs(m[2]), stops: elements(m[3], 'stop') };
}

const hex2 = a => Math.round(Math.max(0, Math.min(1, a)) * 255).toString(16).padStart(2, '0').toUpperCase();
const argb = (color, alpha = 1) => '#' + hex2(alpha) + color.replace('#', '').toUpperCase();

function gradientXml(id, indent) {
  const g = gradients[id];
  const pos = g.type === 'linear'
    ? `android:type="linear" android:startX="${g.x1}" android:startY="${g.y1}" android:endX="${g.x2}" android:endY="${g.y2}"`
    : `android:type="radial" android:centerX="${g.cx}" android:centerY="${g.cy}" android:gradientRadius="${g.r}"`;
  const items = g.stops.map(s => `${indent}    <item android:offset="${s.offset}" android:color="${argb(s.stopColor, s.stopOpacity == null ? 1 : +s.stopOpacity)}" />`);
  return [`${indent}<gradient ${pos}>`, ...items, `${indent}</gradient>`].join('\n');
}

function pathXml(p, white = false) {
  const lines = [`    <path`, `        android:pathData="${p.d}"`];
  const paint = (kind, value) => {
    if (value === 'currentColor' || white) { lines.push(`        android:${kind}Color="#FFFFFFFF"`); return null; }
    const ref = value.match(/^url\(#(.+)\)$/);
    if (!ref) { lines.push(`        android:${kind}Color="${argb(value)}"`); return null; }
    return ref[1];
  };
  let gradient = null, gradientKind = null;
  if (p.fill && p.fill !== 'none') { gradient = paint('fill', p.fill); gradientKind = 'fill'; }
  if (p.fillOpacity) lines.push(`        android:fillAlpha="${+p.fillOpacity}"`);
  if (p.fillRule === 'evenodd') lines.push(`        android:fillType="evenOdd"`);
  if (p.stroke) {
    const g = paint('stroke', p.stroke);
    if (g) { gradient = g; gradientKind = 'stroke'; }
    lines.push(`        android:strokeWidth="${p.strokeWidth}"`);
    if (p.strokeLinecap) lines.push(`        android:strokeLineCap="${p.strokeLinecap}"`);
    if (p.strokeLinejoin) lines.push(`        android:strokeLineJoin="${p.strokeLinejoin}"`);
    if (p.strokeOpacity) lines.push(`        android:strokeAlpha="${+p.strokeOpacity}"`);
  }
  if (!gradient) return lines.join('\n') + ' />';
  return [lines.join('\n') + '>', `        <aapt:attr name="android:${gradientKind}Color">`, gradientXml(gradient, '            '), `        </aapt:attr>`, `    </path>`].join('\n');
}

const vector = (comment, paths, white) => `<?xml version="1.0" encoding="utf-8"?>
<!-- ${comment} Generated by tools/icon/export.js from the handoff (variant 1b); do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
${paths.map(p => pathXml(p, white)).join('\n')}
</vector>
`;

// The colour picture: everything up to the ground is the background, from the fingerboard on — the sign.
const all = elements(icon.fg, 'path');
const boardAt = all.findIndex(p => p.fill === 'url(#b-board)');
if (boardAt < 0) throw new Error('the fingerboard is not in the handoff any more');
const background = all.slice(0, boardAt);
const foreground = all.slice(boardAt);

// Monochrome: a vector drawable has no masks, so the groove (a black «cut» stroke in the handoff) becomes
// a hole — its stroke outlined as a ribbon and joined to the scroll's circle with the even-odd rule.
const mono = elements(icon.mono, 'path');
const cutAt = mono.findIndex(p => p.class === 'cut');
const cut = mono[cutAt];
const scrollAt = cutAt - 1; // the handoff draws the scroll right before its groove
const pts = [...cut.d.matchAll(/(-?[\d.]+) (-?[\d.]+)/g)].map(m => [+m[1], +m[2]]);
const half = +cut.strokeWidth / 2;
const left = [], right = [];
pts.forEach((p, i) => {
  const a = pts[Math.max(0, i - 1)], b = pts[Math.min(pts.length - 1, i + 1)];
  const len = Math.hypot(b[0] - a[0], b[1] - a[1]) || 1;
  const nx = -(b[1] - a[1]) / len * half, ny = (b[0] - a[0]) / len * half;
  left.push([p[0] + nx, p[1] + ny]);
  right.push([p[0] - nx, p[1] - ny]);
});
const r1 = n => String(Math.round(n * 100) / 100);
const ribbon = 'M' + left.concat(right.reverse()).map(p => r1(p[0]) + ' ' + r1(p[1])).join('L') + 'Z';
const scroll = { ...mono[scrollAt], d: mono[scrollAt].d + ribbon, fillRule: 'evenodd' };
const monoPaths = mono.map((p, i) => (i === scrollAt ? scroll : p)).filter((_, i) => i !== cutAt);

const out = path.join(root, 'app/src/main/res/drawable');
fs.writeFileSync(path.join(out, 'ic_launcher_background.xml'), vector('Launcher icon, background: evening sky, sun and ground.', background));
fs.writeFileSync(path.join(out, 'ic_launcher_foreground.xml'), vector('Launcher icon, foreground: the fingerboard as a road, the head against the sun.', foreground));
fs.writeFileSync(path.join(out, 'ic_launcher_monochrome.xml'), vector('Launcher icon, monochrome layer for themed icons.', monoPaths, true));
console.log(`background ${background.length} paths, foreground ${foreground.length}, monochrome ${monoPaths.length}`);

// The stores' icon: 512 × 512, a full square — the store rounds the corners and adds the shadow itself.
// It shows what a launcher shows, the middle 72 of the 108 grid, so the sign is as large as on the phone.
// Rendered by headless Chrome, the one SVG renderer every Mac here has.
const kebab = s => s.replace(/\b(stopColor|stopOpacity|strokeWidth|strokeLinecap|strokeLinejoin|strokeOpacity|fillOpacity|fillRule)=/g,
  (_, a) => a.replace(/[A-Z]/g, c => '-' + c.toLowerCase()) + '=');
// The four-pointed star in the upper left corner would be half cut by the store's rounding: left out here.
const storeFg = icon.fg.replace(/<path d="[^"]*Q[^"]*" fill="#FFF1D6"><\/path>/, '');
if (storeFg === icon.fg) throw new Error('the star is not in the handoff any more');
const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="18 18 72 72"><defs>${kebab(icon.defs)}</defs>${kebab(storeFg)}</svg>`;
const store = path.join(root, 'docs/store');
fs.mkdirSync(store, { recursive: true });
const page = path.join(store, 'icon-512.html');
fs.writeFileSync(page, `<!doctype html><html><body style="margin:0;overflow:hidden">${svg}</body></html>`);
const chrome = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
execFileSync(chrome, ['--headless', '--disable-gpu', '--hide-scrollbars', '--force-device-scale-factor=1', '--window-size=512,512',
  `--screenshot=${path.join(store, 'icon-512.png')}`, 'file://' + page], { stdio: 'ignore' });
fs.unlinkSync(page);
console.log('store icon docs/store/icon-512.png');

// Google Play's feature graphic: 1024 × 500, the icon's scene widened — the sun and the road on the
// right, the name on the evening sky at the left. No tagline: the banner serves every language of the
// listing. The sky, the ground and both hills are carried out past the icon's square to fill the width.
const wide = storeFg
  .split('M-18 -18H126V126H-18Z').join('M-200 -18H300V126H-200Z')
  .split('M-18 62H126V126H-18Z').join('M-200 62H300V126H-200Z')
  .replace('M-18 62V56C', 'M-200 62V57.5C-120 57 -60 56.2 -18 56C')
  .replace('M126 62V54.6C', 'M300 62V56C220 55.6 160 54.8 126 54.6C');
const [bw, bh] = [1024, 500];
const vy = 19, vh = 70, vw = vh * bw / bh, vx = -45; // the sun at about seven tenths of the width
const font = path.join(root, 'app/src/main/res/font/manrope_variable.ttf');
const banner = `<!doctype html><html><head><style>
@font-face { font-family: Manrope; src: url('file://${font}'); font-weight: 200 800; }
body { margin: 0; width: ${bw}px; height: ${bh}px; overflow: hidden; position: relative; }
svg { position: absolute; inset: 0; }
h1 { position: absolute; left: 72px; top: 92px; margin: 0; font: 800 84px/0.98 Manrope; letter-spacing: -1.5px;
     color: #FFF1D6; text-shadow: 0 2px 24px rgba(42, 40, 87, 0.45); }
</style></head><body>
<svg xmlns="http://www.w3.org/2000/svg" width="${bw}" height="${bh}" viewBox="${vx} ${vy} ${vw} ${vh}" preserveAspectRatio="xMidYMid slice"><defs>${kebab(icon.defs)}</defs>${kebab(wide)}</svg>
<h1>Violin<br>Journey</h1>
</body></html>`;
const bannerPage = path.join(store, 'feature-graphic.html');
fs.writeFileSync(bannerPage, banner);
execFileSync(chrome, ['--headless', '--disable-gpu', '--hide-scrollbars', '--force-device-scale-factor=1', `--window-size=${bw},${bh}`,
  '--virtual-time-budget=2000', `--screenshot=${path.join(store, 'feature-graphic.png')}`, 'file://' + bannerPage], { stdio: 'ignore' });
fs.unlinkSync(bannerPage);
console.log('feature graphic docs/store/feature-graphic.png');
