package com.violinjourney.app.feature.journey.art

/** Colours of the places drawn after the handoff — generated by tools/journey/export.js from `EXTRA_LOCPAL` in extra-scenes.js: changed there, regenerated here. */
internal object ExtraScenePalettes {
    val locations: Map<String, Map<String, Long>> = mapOf(
        "prague" to mapOf(
            "stone" to 0xFFD8C39A, "stoneLit" to 0xFFE8D7B2, "stoneShade" to 0xFFB39B72, "stoneBase" to 0xFFC2AC82, "trim" to 0xFFF2ECD8,
            "roof" to 0xFF5E7A74, "roofLit" to 0xFF7C9A92, "dark" to 0xFF3A3040, "statue" to 0xFF8A8478,
        ),
        "leipzig" to mapOf(
            "plaster" to 0xFFEFE7D6, "plasterShade" to 0xFFD2C7B0, "roofTile" to 0xFF9A4B3A, "roofTileLit" to 0xFFB8614C, "roofTileShade" to 0xFF74372B,
            "copper" to 0xFF5E8F80, "copperLit" to 0xFF7FAF9F, "dark" to 0xFF3A3040, "stoneBase" to 0xFFB9AE98,
        ),
        "berlin" to mapOf(
            "ochre" to 0xFFD9A441, "ochreLit" to 0xFFECC062, "ochreShade" to 0xFFB07F2C, "ochreDark" to 0xFF8C6420, "glass" to 0xFF6F7F93,
            "concrete" to 0xFFCFC8BC, "concreteShade" to 0xFFABA498, "dark" to 0xFF3A3040,
        ),
        "amsterdam" to mapOf(
            "brick" to 0xFFA85C44, "brickLit" to 0xFFC0735A, "brickShade" to 0xFF82432F, "stone" to 0xFFEDE3CF, "stoneShade" to 0xFFCFC3AA,
            "roof" to 0xFF4E5560, "roofLit" to 0xFF6A727E, "gold" to 0xFFE2B74E, "dark" to 0xFF3A3040, "quay" to 0xFF6E5A4E,
            "quayLit" to 0xFF8A7466, "boat" to 0xFF3E5A4C, "boatLit" to 0xFFC9B48A,
        ),
        "paris" to mapOf(
            "stone" to 0xFFDCCDB0, "stoneLit" to 0xFFECDFC4, "stoneShade" to 0xFFB8A685, "stoneBase" to 0xFFC9B995, "trim" to 0xFFF3ECDA,
            "copper" to 0xFF5F9485, "copperLit" to 0xFF84B5A4, "gold" to 0xFFE2B74E, "dark" to 0xFF3A3040,
        ),
        "spb" to mapOf(
            "wall" to 0xFFDDB653, "wallLit" to 0xFFEBCB74, "wallShade" to 0xFFB3933F, "wallBase" to 0xFFC4A148, "trim" to 0xFFF6F1E4,
            "roof" to 0xFF7A8084, "roofLit" to 0xFF979DA1, "gold" to 0xFFE2B74E, "dark" to 0xFF3A3040,
        ),
        "moscow" to mapOf(
            "wall" to 0xFFEAD9A8, "wallLit" to 0xFFF5E8C2, "wallShade" to 0xFFC4B281, "wallBase" to 0xFFD3C293, "trim" to 0xFFF8F4EA,
            "roof" to 0xFF6F8278, "roofLit" to 0xFF8DA096, "bronze" to 0xFF3F4E47, "plinth" to 0xFF8F4A3C, "plinthLit" to 0xFFA96152,
            "dark" to 0xFF3A3040,
        ),
        "newyork" to mapOf(
            "brick" to 0xFFB5683C, "brickLit" to 0xFFCC7F50, "brickShade" to 0xFF8A4C2A, "trim" to 0xFFDDBB92, "marquee" to 0xFF2E2A38,
            "taxi" to 0xFFF2C230, "taxiShade" to 0xFFC99A16, "taxiDark" to 0xFF2A2430, "dark" to 0xFF3A3040,
        ),
        "buenosaires" to mapOf(
            "stone" to 0xFFE4D6BC, "stoneLit" to 0xFFF1E6CF, "stoneShade" to 0xFFBBAA8A, "stoneBase" to 0xFFCDBE9F, "trim" to 0xFFF7F1E2,
            "roof" to 0xFF7D6A5A, "roofLit" to 0xFF9A8675, "dark" to 0xFF3A3040,
        ),
        "tokyo" to mapOf(
            "tile" to 0xFFB9A48C, "tileLit" to 0xFFCDB9A0, "tileShade" to 0xFF8F7C66, "glass" to 0xFF6F8AA0, "steel" to 0xFF9AA3AD,
            "steelLit" to 0xFFBCC5CE, "steelShade" to 0xFF6E7781, "towerRed" to 0xFFD8452E, "towerWhite" to 0xFFF2EFE6, "blossom" to 0xFFF2B6C8,
            "blossomLit" to 0xFFFAD3DE, "blossomShade" to 0xFFD48BA4, "gold" to 0xFFE2B74E, "dark" to 0xFF3A3040,
        ),
        "salzburgInt" to mapOf(
            "seat" to 0xFF8E2F3F, "seatDark" to 0xFF5A1E2A, "wood" to 0xFFA9713F, "ceil" to 0xFFF3EEE2, "ceilShade" to 0xFFDDD5C2,
            "back" to 0xFFE8E0CE, "wallL" to 0xFFF0E9D9, "wallR" to 0xFFCFC6B1, "floor" to 0xFF5A1E2A, "rail" to 0xFFE2B74E,
            "railShade" to 0xFFB08A45, "organCase" to 0xFF7A5B3A, "pipe" to 0xFFE9C98D, "pipeShade" to 0xFFB08A45,
        ),
        "pragueInt" to mapOf(
            "ceil" to 0xFFEFE6D0, "ceilShade" to 0xFFD8CCAE, "back" to 0xFFC9B78F, "wallL" to 0xFFE3D6B6, "wallR" to 0xFFBBAA82,
            "floor" to 0xFF2F3A55, "rail" to 0xFFE2B74E, "railShade" to 0xFFB08A45, "column" to 0xFFF6F1E4, "columnShade" to 0xFFCFC6B1,
            "organCase" to 0xFF5E4630, "pipe" to 0xFFD7DCE2, "pipeShade" to 0xFF9AA3AD, "seat" to 0xFF3E5A8A, "seatDark" to 0xFF27395C,
            "wood" to 0xFFA9713F,
        ),
        "leipzigInt" to mapOf(
            "vault" to 0xFFEDE7DA, "vaultLit" to 0xFFF7F3EA, "vaultShade" to 0xFFCFC7B6, "rib" to 0xFFA8503E, "pier" to 0xFFF2ECDF,
            "pierShade" to 0xFFBFB6A2, "floor" to 0xFF8A7F72, "aisle" to 0xFFB3A898, "wood" to 0xFF6E4B2E, "woodShade" to 0xFF4E341F,
        ),
        "berlinInt" to mapOf(
            "hallDark" to 0xFF2B2622, "ceil" to 0xFFE9DFC8, "ceilShade" to 0xFFC7BA9C, "ceilLit" to 0xFFF5EDDA, "terrace" to 0xFFC9A15C,
            "terraceShade" to 0xFFA9834A, "seat" to 0xFF5E4A30, "stage" to 0xFFD9B27A, "stageLit" to 0xFFF0D6A6, "stageShade" to 0xFF8E6E36,
            "cloud" to 0xFFF7F2E6, "cloudShade" to 0xFFBDB39C, "organCase" to 0xFF8E6E36, "pipe" to 0xFFD7DCE2, "pipeShade" to 0xFF9AA3AD,
        ),
        "amsterdamInt" to mapOf(
            "seat" to 0xFF8E2F3F, "seatDark" to 0xFF5A1E2A, "wood" to 0xFFA9713F, "ceil" to 0xFFF4EFE3, "ceilShade" to 0xFFDED6C3,
            "back" to 0xFFE6DDC9, "wallL" to 0xFFEFE8D8, "wallR" to 0xFFCCC3AE, "floor" to 0xFF5A1E2A, "rail" to 0xFFF8F4EA,
            "railShade" to 0xFFCFC6B1, "organCase" to 0xFF6B3F2A, "pipe" to 0xFFE9C98D, "pipeShade" to 0xFFB08A45,
        ),
        "parisInt" to mapOf(
            "hallDark" to 0xFF4A1622, "ceil" to 0xFFE9C98D, "ceilShade" to 0xFFC9A15C, "tier" to 0xFFB8863B, "tierShade" to 0xFF9A6E2C,
            "rail" to 0xFFE2B74E, "railLit" to 0xFFF3D98C, "box" to 0xFF3A1220, "seat" to 0xFF9B2C3E, "seatDark" to 0xFF5A1E2A,
            "curtain" to 0xFF7A2030, "wood" to 0xFFA9713F,
        ),
        "londonInt" to mapOf(
            "hallDark" to 0xFF3A1820, "ceil" to 0xFFC9CFD6, "ceilShade" to 0xFF9FA8B2, "tier" to 0xFFD9C7A6, "tierShade" to 0xFFBCA780,
            "rail" to 0xFFE2B74E, "railLit" to 0xFFF3D98C, "box" to 0xFF4A1E28, "seat" to 0xFFA8323F, "seatDark" to 0xFF5A1E2A,
            "mushroom" to 0xFFF2EFE6, "mushroomShade" to 0xFF9A9488, "organCase" to 0xFF5E4630, "pipe" to 0xFFD7DCE2, "pipeShade" to 0xFF9AA3AD,
            "wood" to 0xFFA9713F,
        ),
        "spbInt" to mapOf(
            "seat" to 0xFF8E2F3F, "seatDark" to 0xFF5A1E2A, "wood" to 0xFFA9713F, "ceil" to 0xFFF7F4EC, "ceilShade" to 0xFFE0DBCF,
            "back" to 0xFFEDE8DC, "wallL" to 0xFFF4F0E6, "wallR" to 0xFFD2CCBE, "floor" to 0xFF5A1E2A, "rail" to 0xFFF8F4EA,
            "railShade" to 0xFFCFC6B1, "column" to 0xFFFFFFFF, "columnShade" to 0xFFD2CCBE, "organCase" to 0xFF6B4A30, "pipe" to 0xFFD7DCE2,
            "pipeShade" to 0xFF9AA3AD,
        ),
        "moscowInt" to mapOf(
            "ceil" to 0xFFF3EEE0, "ceilShade" to 0xFFDCD4C0, "back" to 0xFFE4DAC2, "wallL" to 0xFFEFE7D2, "wallR" to 0xFFCBC1A8,
            "floor" to 0xFF6E5A3E, "rail" to 0xFFF8F4EA, "railShade" to 0xFFCFC6B1, "trim" to 0xFFF8F4EA, "portrait" to 0xFF4E4438,
            "organCase" to 0xFF5E4630, "pipe" to 0xFFD7DCE2, "pipeShade" to 0xFF9AA3AD, "seat" to 0xFFA98B5A, "seatDark" to 0xFF7A6340,
            "wood" to 0xFFA9713F,
        ),
        "newyorkInt" to mapOf(
            "hallDark" to 0xFF3A2A24, "ceil" to 0xFFF5F0E4, "ceilShade" to 0xFFDDD5C2, "tier" to 0xFFF3EEE2, "tierShade" to 0xFFDAD2BF,
            "rail" to 0xFFE2B74E, "railLit" to 0xFFF3D98C, "box" to 0xFF4A2A24, "seat" to 0xFFA8323F, "seatDark" to 0xFF5A1E2A,
            "wood" to 0xFFA9713F,
        ),
        "buenosairesInt" to mapOf(
            "hallDark" to 0xFF3F1A22, "ceil" to 0xFFE6D6B8, "ceilShade" to 0xFFC6B48F, "tier" to 0xFFE9DDC4, "tierShade" to 0xFFCBBE9F,
            "rail" to 0xFFE2B74E, "railLit" to 0xFFF3D98C, "box" to 0xFF4A1E2A, "seat" to 0xFFB0485A, "seatDark" to 0xFF6A2636,
            "curtain" to 0xFF8A2A3A, "wood" to 0xFFA9713F,
        ),
        "tokyoInt" to mapOf(
            "hallDark" to 0xFF2A2018, "ceil" to 0xFFE8D3AE, "ceilShade" to 0xFFC5AC80, "ceilLit" to 0xFFF4E3C2, "terrace" to 0xFFB98A54,
            "terraceShade" to 0xFF976C3C, "seat" to 0xFF7A2E36, "stage" to 0xFFE2C08A, "stageLit" to 0xFFF5DDB0, "stageShade" to 0xFF8E6A3C,
            "organCase" to 0xFF8E6A3C, "pipe" to 0xFFE1E5EA, "pipeShade" to 0xFF9AA3AD,
        ),
        "sydneyInt" to mapOf(
            "ceil" to 0xFFEAD9B8, "ceilShade" to 0xFFC9B48A, "back" to 0xFFD9C49A, "wallL" to 0xFFE2CFA6, "wallR" to 0xFFBFA97C,
            "floor" to 0xFF3A2A36, "rail" to 0xFFF2E6CC, "railShade" to 0xFFC9B48A, "organCase" to 0xFFA98458, "pipe" to 0xFFE1E5EA,
            "pipeShade" to 0xFF9AA3AD, "petal" to 0xFFC2307E, "petalLit" to 0xFFE66AAE, "seat" to 0xFF8C2A6E, "seatDark" to 0xFF5A1A48,
            "wood" to 0xFFC99A5E,
        ),
        "cremonaOut" to mapOf(
            "brick" to 0xFFB8694A, "brickLit" to 0xFFCF8262, "brickShade" to 0xFF8E4C33, "marble" to 0xFFF0E6D6, "marbleLit" to 0xFFFBF4E8,
            "marbleShade" to 0xFFD0C3AC, "rose" to 0xFFC98B7A, "spire" to 0xFF6F8278, "spireLit" to 0xFF8DA096, "gold" to 0xFFE2B74E,
            "dark" to 0xFF3A3040,
        ),
        "milanOut" to mapOf(
            "stone" to 0xFFE6D8B8, "stoneLit" to 0xFFF2E7CC, "stoneShade" to 0xFFBEAF8C, "stoneBase" to 0xFFCDBE9C, "trim" to 0xFFF8F2E2,
            "roof" to 0xFF7A6A5C, "roofLit" to 0xFF978676, "dark" to 0xFF3A3040, "tram" to 0xFFE9B23C, "tramShade" to 0xFFC28E22,
            "tramRoof" to 0xFFEDE4CF, "tramDark" to 0xFF2A2430,
        ),
        "viennaStage" to mapOf(
            "hvoid" to 0xFF140F1C, "hwall" to 0xFF3A3048, "hwallLit" to 0xFF4A3E5C, "hwallSh" to 0xFF241D30, "hgold" to 0xFFE2B74E,
            "hgoldLit" to 0xFFF2D488, "hgoldSh" to 0xFFA8863A, "hseat" to 0xFF8E2F3F, "hseatLit" to 0xFFA8323F, "hseatSh" to 0xFF5A1E2A,
            "hcream" to 0xFFF3EEE2, "hcreamSh" to 0xFFD8D0BE, "hboard" to 0xFF8B5E3C, "hboardSh" to 0xFF6E4A34, "hchand" to 0xFFFFE9B0,
            "hdark" to 0xFF1C1530, "hwood" to 0xFFA9713F, "hwoodSh" to 0xFF7E5230, "hstone" to 0xFFCFC6B4, "hstoneSh" to 0xFFA89E8C,
        ),
        "salzburgStage" to mapOf(
            "hvoid" to 0xFF140F1C, "hwall" to 0xFFE8E0CE, "hwallLit" to 0xFFF3EEE2, "hwallSh" to 0xFFCFC6B1, "hgold" to 0xFFE2B74E,
            "hgoldLit" to 0xFFF2D488, "hgoldSh" to 0xFFA8863A, "hseat" to 0xFF8E2F3F, "hseatLit" to 0xFFA8323F, "hseatSh" to 0xFF5A1E2A,
            "hcream" to 0xFFF3EEE2, "hcreamSh" to 0xFFD8D0BE, "hboard" to 0xFF8B5E3C, "hboardSh" to 0xFF6E4A34, "hchand" to 0xFFFFE9B0,
            "hdark" to 0xFF5A4E44, "hwood" to 0xFFA9713F, "hwoodSh" to 0xFF7E5230, "hstone" to 0xFFCFC6B4, "hstoneSh" to 0xFFA89E8C,
        ),
        "pragueStage" to mapOf(
            "hvoid" to 0xFF140F1C, "hwall" to 0xFFC9B78F, "hwallLit" to 0xFFE3D6B6, "hwallSh" to 0xFFA89468, "hgold" to 0xFFE2B74E,
            "hgoldLit" to 0xFFF2D488, "hgoldSh" to 0xFFA8863A, "hseat" to 0xFF3E5A8E, "hseatLit" to 0xFF4E6EA8, "hseatSh" to 0xFF27395C,
            "hcream" to 0xFFF3EEE2, "hcreamSh" to 0xFFD8D0BE, "hboard" to 0xFF8B5E3C, "hboardSh" to 0xFF6E4A34, "hchand" to 0xFFFFE9B0,
            "hdark" to 0xFF1C1530, "hwood" to 0xFFA9713F, "hwoodSh" to 0xFF7E5230, "hstone" to 0xFFCFC6B4, "hstoneSh" to 0xFFA89E8C,
        ),
        "amsterdamStage" to mapOf(
            "hvoid" to 0xFF140F1C, "hwall" to 0xFFE6DDC9, "hwallLit" to 0xFFEFE8D8, "hwallSh" to 0xFFCCC3AE, "hgold" to 0xFFE2B74E,
            "hgoldLit" to 0xFFF2D488, "hgoldSh" to 0xFFA8863A, "hseat" to 0xFF8E2F3F, "hseatLit" to 0xFFA8323F, "hseatSh" to 0xFF5A1E2A,
            "hcream" to 0xFFF3EEE2, "hcreamSh" to 0xFFD8D0BE, "hboard" to 0xFF8B5E3C, "hboardSh" to 0xFF6E4A34, "hchand" to 0xFFFFE9B0,
            "hdark" to 0xFF1C1530, "hwood" to 0xFFA9713F, "hwoodSh" to 0xFF7E5230, "hstone" to 0xFFCFC6B4, "hstoneSh" to 0xFFA89E8C,
        ),
        "spbStage" to mapOf(
            "hvoid" to 0xFF140F1C, "hwall" to 0xFFEDE8DC, "hwallLit" to 0xFFF7F4EC, "hwallSh" to 0xFFD2CCBE, "hgold" to 0xFFE2B74E,
            "hgoldLit" to 0xFFF2D488, "hgoldSh" to 0xFFA8863A, "hseat" to 0xFF8E2F3F, "hseatLit" to 0xFFA8323F, "hseatSh" to 0xFF5A1E2A,
            "hcream" to 0xFFFFFFFF, "hcreamSh" to 0xFFD2CCBE, "hboard" to 0xFF8B5E3C, "hboardSh" to 0xFF6E4A34, "hchand" to 0xFFFFE9B0,
            "hdark" to 0xFF1C1530, "hwood" to 0xFFA9713F, "hwoodSh" to 0xFF7E5230, "hstone" to 0xFFCFC6B4, "hstoneSh" to 0xFFA89E8C,
        ),
        "moscowStage" to mapOf(
            "hvoid" to 0xFF140F1C, "hwall" to 0xFFE4DAC2, "hwallLit" to 0xFFEFE7D2, "hwallSh" to 0xFFCBC1A8, "hgold" to 0xFFE2B74E,
            "hgoldLit" to 0xFFF2D488, "hgoldSh" to 0xFFA8863A, "hseat" to 0xFFA98B5A, "hseatLit" to 0xFFBFA06E, "hseatSh" to 0xFF7A6340,
            "hcream" to 0xFFF3EEE2, "hcreamSh" to 0xFFD8D0BE, "hboard" to 0xFF8B5E3C, "hboardSh" to 0xFF6E4A34, "hchand" to 0xFFFFE9B0,
            "hdark" to 0xFF1C1530, "hwood" to 0xFFA9713F, "hwoodSh" to 0xFF7E5230, "hstone" to 0xFFCFC6B4, "hstoneSh" to 0xFFA89E8C,
            "hportrait" to 0xFF4E4438,
        ),
        "sydneyStage" to mapOf(
            "hvoid" to 0xFF140F1C, "hwall" to 0xFFD9C49A, "hwallLit" to 0xFFE2CFA6, "hwallSh" to 0xFFBFA97C, "hgold" to 0xFFE2B74E,
            "hgoldLit" to 0xFFF2D488, "hgoldSh" to 0xFFA8863A, "hseat" to 0xFF7A3E8E, "hseatLit" to 0xFF9A5AAE, "hseatSh" to 0xFF4E2458,
            "hcream" to 0xFFF3EEE2, "hcreamSh" to 0xFFD8D0BE, "hboard" to 0xFF8B5E3C, "hboardSh" to 0xFF6E4A34, "hchand" to 0xFFFFE9B0,
            "hdark" to 0xFF1C1530, "hwood" to 0xFFA9713F, "hwoodSh" to 0xFF7E5230, "hstone" to 0xFFCFC6B4, "hstoneSh" to 0xFFA89E8C,
            "hpetal" to 0xFFC2307E, "hpetalLit" to 0xFFE66AAE, "hrib" to 0xFFC9B48A,
        ),
        "parisStage" to mapOf(
            "hvoid" to 0xFF140F1C, "hwall" to 0xFF3A3048, "hwallLit" to 0xFF4A3E5C, "hwallSh" to 0xFF241D30, "hgold" to 0xFFE2B74E,
            "hgoldLit" to 0xFFF2D488, "hgoldSh" to 0xFFA8863A, "hseat" to 0xFF8E2F3F, "hseatLit" to 0xFFA8323F, "hseatSh" to 0xFF5A1E2A,
            "hcream" to 0xFFF3EEE2, "hcreamSh" to 0xFFD8D0BE, "hboard" to 0xFF8B5E3C, "hboardSh" to 0xFF6E4A34, "hchand" to 0xFFFFE9B0,
            "hdark" to 0xFF1C1530, "hwood" to 0xFFA9713F, "hwoodSh" to 0xFF7E5230, "hstone" to 0xFFCFC6B4, "hstoneSh" to 0xFFA89E8C,
        ),
        "milanStage" to mapOf(
            "hvoid" to 0xFF140F1C, "hwall" to 0xFF4A1622, "hwallLit" to 0xFF6E2333, "hwallSh" to 0xFF3A1220, "hgold" to 0xFFE2B74E,
            "hgoldLit" to 0xFFF2D488, "hgoldSh" to 0xFFA8863A, "hseat" to 0xFF9B2C3E, "hseatLit" to 0xFFA8323F, "hseatSh" to 0xFF5A1E2A,
            "hcream" to 0xFFE9C98D, "hcreamSh" to 0xFFC9A15C, "hboard" to 0xFF8B5E3C, "hboardSh" to 0xFF6E4A34, "hchand" to 0xFFFFE9B0,
            "hdark" to 0xFF2A0E16, "hwood" to 0xFFA9713F, "hwoodSh" to 0xFF7E5230, "hstone" to 0xFFCFC6B4, "hstoneSh" to 0xFFA89E8C,
        ),
        "londonStage" to mapOf(
            "hvoid" to 0xFF140F1C, "hwall" to 0xFF3A1820, "hwallLit" to 0xFF5A2A30, "hwallSh" to 0xFF2A1016, "hgold" to 0xFFE2B74E,
            "hgoldLit" to 0xFFF2D488, "hgoldSh" to 0xFFA8863A, "hseat" to 0xFFA8323F, "hseatLit" to 0xFFA8323F, "hseatSh" to 0xFF5A1E2A,
            "hcream" to 0xFFC9CFD6, "hcreamSh" to 0xFF9FA8B2, "hboard" to 0xFF8B5E3C, "hboardSh" to 0xFF6E4A34, "hchand" to 0xFFFFE9B0,
            "hdark" to 0xFF1C1530, "hwood" to 0xFFA9713F, "hwoodSh" to 0xFF7E5230, "hstone" to 0xFFCFC6B4, "hstoneSh" to 0xFFA89E8C,
            "hmush" to 0xFFF2EFE6, "hmushSh" to 0xFF9A9488,
        ),
        "newyorkStage" to mapOf(
            "hvoid" to 0xFF140F1C, "hwall" to 0xFF3A2A24, "hwallLit" to 0xFF5A443A, "hwallSh" to 0xFF2A1E1A, "hgold" to 0xFFE2B74E,
            "hgoldLit" to 0xFFF2D488, "hgoldSh" to 0xFFA8863A, "hseat" to 0xFFA8323F, "hseatLit" to 0xFFA8323F, "hseatSh" to 0xFF5A1E2A,
            "hcream" to 0xFFF5F0E4, "hcreamSh" to 0xFFDDD5C2, "hboard" to 0xFF8B5E3C, "hboardSh" to 0xFF6E4A34, "hchand" to 0xFFFFE9B0,
            "hdark" to 0xFF1C1530, "hwood" to 0xFFA9713F, "hwoodSh" to 0xFF7E5230, "hstone" to 0xFFCFC6B4, "hstoneSh" to 0xFFA89E8C,
            "htier" to 0xFFF3EEE2, "htierSh" to 0xFFDAD2BF,
        ),
        "buenosairesStage" to mapOf(
            "hvoid" to 0xFF140F1C, "hwall" to 0xFF3F1A22, "hwallLit" to 0xFF5A2A34, "hwallSh" to 0xFF2A0E16, "hgold" to 0xFFE2B74E,
            "hgoldLit" to 0xFFF2D488, "hgoldSh" to 0xFFA8863A, "hseat" to 0xFFB0485A, "hseatLit" to 0xFFA8323F, "hseatSh" to 0xFF6A2636,
            "hcream" to 0xFFE6D6B8, "hcreamSh" to 0xFFC6B48F, "hboard" to 0xFF8B5E3C, "hboardSh" to 0xFF6E4A34, "hchand" to 0xFFFFE9B0,
            "hdark" to 0xFF1C1530, "hwood" to 0xFFA9713F, "hwoodSh" to 0xFF7E5230, "hstone" to 0xFFCFC6B4, "hstoneSh" to 0xFFA89E8C,
        ),
        "berlinStage" to mapOf(
            "hvoid" to 0xFF140F1C, "hwall" to 0xFF4A3E38, "hwallLit" to 0xFF5C4E44, "hwallSh" to 0xFF241D30, "hgold" to 0xFFE2B74E,
            "hgoldLit" to 0xFFF2D488, "hgoldSh" to 0xFFA8863A, "hseat" to 0xFF3E6E7A, "hseatLit" to 0xFF4E8899, "hseatSh" to 0xFF284A54,
            "hcream" to 0xFFF3EEE2, "hcreamSh" to 0xFFD8D0BE, "hboard" to 0xFF8B5E3C, "hboardSh" to 0xFF6E4A34, "hchand" to 0xFFFFE9B0,
            "hdark" to 0xFF1C1530, "hwood" to 0xFFA9713F, "hwoodSh" to 0xFF7E5230, "hstone" to 0xFFCFC6B4, "hstoneSh" to 0xFFA89E8C,
        ),
        "tokyoStage" to mapOf(
            "hvoid" to 0xFF140F1C, "hwall" to 0xFF6E4A34, "hwallLit" to 0xFF8A5E42, "hwallSh" to 0xFF4E3424, "hgold" to 0xFFE2B74E,
            "hgoldLit" to 0xFFF2D488, "hgoldSh" to 0xFFA8863A, "hseat" to 0xFF7A2E36, "hseatLit" to 0xFFA8323F, "hseatSh" to 0xFF4A1A22,
            "hcream" to 0xFFE8D3AE, "hcreamSh" to 0xFFC5AC80, "hboard" to 0xFF8B5E3C, "hboardSh" to 0xFF6E4A34, "hchand" to 0xFFFFE9B0,
            "hdark" to 0xFF1C1530, "hwood" to 0xFFB98A54, "hwoodSh" to 0xFF976C3C, "hstone" to 0xFFCFC6B4, "hstoneSh" to 0xFFA89E8C,
        ),
        "leipzigStage" to mapOf(
            "hvoid" to 0xFF140F1C, "hwall" to 0xFFCFC6B4, "hwallLit" to 0xFFE2DACA, "hwallSh" to 0xFFA89E8C, "hgold" to 0xFFE2B74E,
            "hgoldLit" to 0xFFF2D488, "hgoldSh" to 0xFFA8863A, "hseat" to 0xFF6E5238, "hseatLit" to 0xFF8B6A48, "hseatSh" to 0xFF4E3A28,
            "hcream" to 0xFFF3EEE2, "hcreamSh" to 0xFFD8D0BE, "hboard" to 0xFF8B5E3C, "hboardSh" to 0xFF6E4A34, "hchand" to 0xFFFFE9B0,
            "hdark" to 0xFF1C1530, "hwood" to 0xFFA9713F, "hwoodSh" to 0xFF7E5230, "hstone" to 0xFFCFC6B4, "hstoneSh" to 0xFFA89E8C,
        ),
        "cremonaStage" to mapOf(
            "hvoid" to 0xFF140F1C, "hwall" to 0xFF3A3048, "hwallLit" to 0xFF4A3E5C, "hwallSh" to 0xFF241D30, "hgold" to 0xFFE2B74E,
            "hgoldLit" to 0xFFF2D488, "hgoldSh" to 0xFFA8863A, "hseat" to 0xFF8E2F3F, "hseatLit" to 0xFFA8323F, "hseatSh" to 0xFF5A1E2A,
            "hcream" to 0xFFF3EEE2, "hcreamSh" to 0xFFD8D0BE, "hboard" to 0xFF8B5E3C, "hboardSh" to 0xFF6E4A34, "hchand" to 0xFFFFE9B0,
            "hdark" to 0xFF1C1530, "hwood" to 0xFFA9713F, "hwoodSh" to 0xFF7E5230, "hstone" to 0xFFCFC6B4, "hstoneSh" to 0xFFA89E8C,
            "varnish" to 0xFFB5672F, "varnishLight" to 0xFFD9B27A, "varnishDark" to 0xFF6E3A1E, "ebony" to 0xFF1C1A20, "paper" to 0xFFF1EEE6,
            "metal" to 0xFF6B6C78,
        ),
    )
}
