package com.violinjourney.app.feature.journey.art

/** The high sky of the places drawn for the whole screen — generated by tools/journey/export.js from `starField()` and `cloudSet()` in locations.js (the handoff's numbers): changed there, regenerated here. */
internal object HighSky {
    /** x, y, radius, opacity, period of the twinkle in seconds: five numbers a star. */
    val stars = floatArrayOf(
        115.3f, -207.5f, 1.19f, 0.94f, 4.8f,
        373.2f, -243.2f, 1.62f, 0.39f, 6f,
        67.4f, -381.2f, 2.06f, 0.39f, 3.8f,
        12.5f, -427.1f, 1.71f, 0.9f, 5.3f,
        8.8f, -125.5f, 1.12f, 0.65f, 3.1f,
        11.1f, -31.6f, 1.05f, 0.44f, 2.5f,
        313.9f, -140.2f, 1.32f, 0.84f, 5.4f,
        -3.6f, -124.8f, 0.93f, 0.44f, 4.8f,
        115.3f, -313.1f, 1.64f, 0.54f, 5.5f,
        70.7f, -228.2f, 1.14f, 0.69f, 3.9f,
        359.8f, -348.6f, 1.47f, 0.56f, 5f,
        160.6f, -213f, 1.23f, 0.49f, 2.7f,
        217.3f, -210.6f, 1.11f, 0.53f, 4f,
        328.6f, -418f, 1f, 0.42f, 5.5f,
        259.1f, -203.8f, 1.53f, 0.5f, 4.1f,
        265.5f, -308.4f, 1.5f, 0.49f, 3.1f,
        -19.8f, -196.5f, 0.95f, 0.82f, 5.2f,
        146f, -290.8f, 1.27f, 0.5f, 3.5f,
        107.8f, -62.8f, 1.01f, 0.39f, 5.6f,
        182.7f, -157.2f, 0.83f, 0.85f, 3.4f,
        185.7f, -377.2f, 1.75f, 0.57f, 2.4f,
        29f, -295.9f, 1.83f, 0.52f, 4.5f,
        386.2f, -209.7f, 1.36f, 0.93f, 3.3f,
        203.9f, -375.3f, 1.23f, 0.82f, 4.2f,
        332f, 2.3f, 0.87f, 0.9f, 3.8f,
        381.7f, -214.4f, 1.13f, 0.55f, 5.1f,
        375.1f, -27.5f, 0.78f, 0.5f, 3.6f,
        41.6f, -424f, 1.68f, 0.84f, 3.2f,
        109f, -231.2f, 0.88f, 0.71f, 4.7f,
        392.1f, -15.3f, 0.8f, 0.76f, 2.8f,
        131.2f, -75.4f, 0.87f, 0.77f, 2.8f,
        140.5f, -62f, 0.84f, 0.72f, 4.1f,
        401.2f, -229.4f, 1.13f, 0.94f, 2.7f,
        273.9f, -214.2f, 0.85f, 0.71f, 5.2f,
        3.2f, -213.7f, 1.52f, 0.64f, 4f,
        321.6f, -74f, 0.79f, 0.89f, 3.6f,
        79f, -414f, 0.79f, 0.81f, 5.2f,
        -14.2f, -217.6f, 1.08f, 0.84f, 4f,
        79.6f, -389.9f, 0.92f, 0.71f, 4.5f,
        277.4f, -343.4f, 0.86f, 0.86f, 2.8f,
        43.2f, 33.3f, 0.77f, 0.4f, 4.9f,
        286.7f, -288.3f, 0.74f, 0.39f, 2.4f,
        202.8f, -408.2f, 0.79f, 0.94f, 3.5f,
        76.1f, -399.2f, 1.16f, 0.63f, 4.2f,
    )

    /** x, y, half-width, strength, speed in units a second, and the way it rides from…to: seven numbers a cloud. */
    val dayClouds = floatArrayOf(
        60f, -340f, 96f, 0.55f, 2.5f, -186f, 478f,
        197f, -238f, 74f, 0.7f, 1.967f, -301f, 319f,
        334f, -150f, 60f, 0.85f, 1.6f, -424f, 168f,
        171f, -62f, 46f, 1f, 1.233f, -247f, 317f,
        308f, 128f, 34f, 1f, 0.867f, -372f, 168f,
    )

    val eveningClouds = floatArrayOf(
        60f, -62f, 46f, 1f, 1.233f, -136f, 428f,
        197f, 128f, 34f, 1f, 0.867f, -261f, 279f,
    )
}
