// Exports the scenes of «Знакомство» (spec 3.33, handoff series 36) into the app.
//
//   node tools/onboarding/export.js
//
// The handoff draws its scenes with JS builders (onboarding-art.js: one evening, grid 412 × 480, horizon
// y 300). This script runs them and writes feature/onboarding/art/OnboardingArtData.kt — the layers and
// gradients of every scene as data. The phone on the stand (36b) is written once with `zone` in place of
// its colour and with all three marks; the app paints the zone and shows the mark of the moment.
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '../..');
const source = path.join(root, 'docs/design/project/new_onboarding/project/onboarding-art.js');
const out = path.join(root, 'shared/src/commonMain/kotlin/com/violinjourney/app/feature/onboarding/art/OnboardingArtData.kt');

const window = {};
new Function('window', fs.readFileSync(source, 'utf8'))(window);
const A = window.OnboardingArt;

const scenes = [
  ['welcome', 'welcome', undefined],
  ['live', 'live', undefined],
  ['road', 'road', undefined],
  ['data', 'data', undefined],
  ['setupMicrophone', 'setup', { step: 1 }],
  ['setupReference', 'setup', { step: 2 }],
  ['setupTolerance', 'setup', { step: 3 }],
];

const str = s => JSON.stringify(s);
const f = n => {
  const v = Math.round(n * 1000) / 1000;
  return `${Object.is(v, -0) ? 0 : v}f`;
};
const stop = ([offset, color, alpha]) => `ArtStop(${f(offset)}, ${str(color)}, ${f(alpha == null ? 1 : alpha)})`;
const gradient = g => g.type === 'linear'
  ? `ArtGradient.Linear(${f(g.x1)}, ${f(g.y1)}, ${f(g.x2)}, ${f(g.y2)}, listOf(${g.stops.map(stop).join(', ')}))`
  : `ArtGradient.Radial(${f(g.cx)}, ${f(g.cy)}, ${f(g.r)}, listOf(${g.stops.map(stop).join(', ')}))`;
const layer = l => {
  const args = [str(l.d), `depth = ${l.depth}`];
  if (l.fill) args.push(`fill = ${str(l.fill)}`);
  if (l.stroke) args.push(`stroke = ${str(l.stroke)}`, `strokeWidth = ${f(l.sw)}`);
  if (l.op != null) args.push(`opacity = ${f(l.op)}`);
  if (l.anim) args.push(`motion = ${str(l.anim)}`);
  if (l.evenOdd) args.push('evenOdd = true');
  if (l.fade) args.push('fade = true');
  return `ArtLayer(${args.join(', ')})`;
};

const lines = [
  '// Generated by tools/onboarding/export.js from docs/design/project/new_onboarding/project/onboarding-art.js: do not edit by hand.',
  'package com.violinjourney.app.feature.onboarding.art',
  '',
  'object OnboardingArtData {',
  `    const val WIDTH = ${f(A.W)}`,
  `    const val HEIGHT = ${f(A.H)}`,
  `    const val HORIZON = ${f(A.HZ)}`,
];
for (const [name, key, opt] of scenes) {
  const s = A.scene(key, opt);
  lines.push('', `    val ${name}: ArtScene by lazy {`, '        ArtScene(', '            gradients = mapOf(');
  for (const [n, g] of Object.entries(s.grads)) lines.push(`                ${str(n)} to ${gradient(g)},`);
  lines.push('            ),', '            layers = listOf(');
  for (const l of s.layers) lines.push(`                ${layer(l)},`);
  lines.push('            ),', '        )', '    }');
}
lines.push('}', '');
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, lines.join('\n'));
console.log(`wrote ${path.relative(root, out)}: ${scenes.length} scenes`);
