// Exports the postcards of the journey (spec 3.23) into the app.
//
//   node tools/journey/export.js [previewDir]
//
// The scenes of the design handoff are JS functions that return layers; this script cuts that part
// out of `Путешествие.dc.html`, runs it together with the scenes drawn after the handoff
// (extra-scenes.js, same helpers, same tokens) and writes
//   app/src/main/assets/journey/<scene>.<eve|day>.scene   — a line per layer, tab-separated
//   feature/journey/art/JourneySilhouettes.kt             — the stamps
//   feature/journey/art/ExtraScenePalettes.kt             — the colours of the places drawn after the handoff
// The halls seen from the stage, where Live takes place (spec 3.27), are stage-scenes.js: `<stop>Stage`.
// Every scene says how far up and down it is drawn — `frame=top,bottom` in its header: the full screen
// of a stop never looks past it (spec 3.23). A card alone is 0…260, a hall from the stage −240…480, a
// place drawn for the whole screen −420…600 like the rooms of the home: its definition says `frame: [top, bottom]`.
// With previewDir it also writes an SVG of every scene, drawn the way the handoff draws them.
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '../..');
const handoffDir = path.join(root, 'docs/design/project/journey/project');
// the file name is Cyrillic and stored decomposed on macOS: found, not typed
const handoff = fs.readdirSync(handoffDir).find(f => f.normalize('NFC').startsWith('Путешествие') && f.endsWith('.dc.html'));
const html = fs.readFileSync(path.join(handoffDir, handoff), 'utf8');

const cut = (from, to) => {
  const a = html.indexOf(from);
  const b = html.indexOf(to, a);
  if (a < 0 || b < 0) throw new Error(`the handoff has changed: «${from}» … «${to}» not found`);
  return html.slice(a, b);
};
const helpers = cut('const hex2 =', 'let gid = 0;');
const scenes = cut('const SCENES =', 'const scene =');
const silhouettes = cut('const SIL =', 'const LOC =');
const extra = fs.readFileSync(path.join(__dirname, 'extra-scenes.js'), 'utf8');
const stage = fs.readFileSync(path.join(__dirname, 'stage-scenes.js'), 'utf8');

const result = new Function(`${helpers}\n${scenes}\n${silhouettes}\n${extra}\n${stage}\nreturn { EXTRA_INSERTS, SCENES: { ...SCENES, ...EXTRA_SCENES }, SIL, BASE, LOCPAL: { ...LOCPAL, ...EXTRA_LOCPAL }, EXTRA_LOCPAL, AER, mix };`)();
const { EXTRA_INSERTS, SCENES, SIL, BASE, LOCPAL, EXTRA_LOCPAL, AER, mix } = result;

const CARD_FRAME = [0, 260];
const STAGE_FRAME = [-240, 480];
const out = path.join(root, 'app/src/main/assets/journey');
fs.mkdirSync(out, { recursive: true });
const num = v => (v === undefined ? '' : String(v));
const previewDir = process.argv[2];
if (previewDir) fs.mkdirSync(previewDir, { recursive: true });

for (const [key, s] of Object.entries(SCENES)) {
  for (const eve of [true, false]) {
    const mode = eve ? 'eve' : 'day';
    const layers = (EXTRA_INSERTS[key] || (x => x))(s.fn(eve), eve);
    const aerial = s.aerial !== false;
    const frame = s.frame || (s.stage ? STAGE_FRAME : CARD_FRAME);
    const lines = ['# generated by tools/journey/export.js: do not edit by hand', `loc=${s.loc};aerial=${aerial ? 1 : 0};frame=${frame.join(',')}`];
    layers.forEach(l => lines.push([l.fill, l.depth, num(l.op), num(l.tx), num(l.ty), num(l.sc), l.glow ? 1 : '', l.stroke || '', num(l.sw), l.fillNone ? 1 : '', l.d, l.anim || ''].join('\t')));
    fs.writeFileSync(path.join(out, `${key}.${mode}.scene`), lines.join('\n') + '\n');
    console.log(`${key}.${mode}: ${layers.length} layers`);
    if (previewDir) fs.writeFileSync(path.join(previewDir, `${key}.${mode}.svg`), svgOf(layers, { ...BASE[mode], ...(LOCPAL[s.loc] || {}) }, aerial, frame));
  }
}

// a scene is seen whole, as far up and down as it is drawn: a hall from its ceiling to the boards under our feet
function svgOf(layers, pal, aerial, [top, bottom]) {
  const col = (t, depth) => {
    const c = t.startsWith('#') || t.startsWith('rgba') ? t : (pal[t] ?? 'magenta');
    return aerial && depth < 2 && c.startsWith('#') ? mix(c, pal.skyLow, AER[depth]) : c;
  };
  const els = layers.map(l => {
    const fill = l.fill === 'SKY' ? 'url(#s)' : l.fill === 'GLOW' ? 'url(#g)' : l.glow ? 'url(#w)' : col(l.fill, l.depth);
    const attrs = [`d="${l.d}"`, `fill="${l.fillNone ? 'none' : fill}"`];
    if (l.op !== undefined) attrs.push(`opacity="${l.op}"`);
    if (l.stroke) attrs.push(`stroke="${col(l.stroke, l.depth)}"`, `stroke-width="${l.sw}"`, 'stroke-linecap="round"');
    if (l.tx !== undefined) attrs.push(`transform="translate(${l.tx} ${l.ty}) scale(${l.sc || 1})"`);
    return `<path ${attrs.join(' ')}/>`;
  });
  const stop = (o, c) => { const m = c.match(/rgba\((\d+),(\d+),(\d+),([\d.]+)\)/); return m ? `<stop offset="${o}" stop-color="rgb(${m[1]},${m[2]},${m[3]})" stop-opacity="${m[4]}"/>` : `<stop offset="${o}" stop-color="${c}"/>`; };
  const box = `width="824" height="${2 * (bottom - top)}" viewBox="0 ${top} 412 ${bottom - top}"`;
  return `<svg xmlns="http://www.w3.org/2000/svg" ${box}><defs>` +
    `<linearGradient id="s" x1="0" y1="0" x2="0" y2="1">${stop(0, pal.sky)}${stop(1, pal.skyLow)}</linearGradient>` +
    `<radialGradient id="g">${stop(0, pal.glow)}${stop(1, 'rgba(255,196,110,0)')}</radialGradient>` +
    `<radialGradient id="w">${stop(0, 'rgba(255,196,110,.55)')}${stop(1, 'rgba(255,196,110,0)')}</radialGradient></defs>${els.join('')}</svg>`;
}

const kt = ['package com.example.violintuner.feature.journey.art', '', '/** Silhouettes of the stops (grid 200 × 120) — generated by tools/journey/export.js from the design handoff `Путешествие.dc.html`, array `SIL`: changed there, regenerated here. */', 'internal object JourneySilhouettes {', '    val paths: Map<String, List<String>> = mapOf('];
for (const [k, v] of Object.entries(SIL)) kt.push(`        "${k}" to listOf(${v.map(d => JSON.stringify(d)).join(', ')}),`);
kt.push('    )', '}', '');
fs.writeFileSync(path.join(root, 'app/src/main/java/com/example/violintuner/feature/journey/art/JourneySilhouettes.kt'), kt.join('\n'));

const art = path.join(root, 'app/src/main/java/com/example/violintuner/feature/journey/art');
const pk = ['package com.example.violintuner.feature.journey.art', '', '/** Colours of the places drawn after the handoff — generated by tools/journey/export.js from `EXTRA_LOCPAL` in extra-scenes.js: changed there, regenerated here. */', 'internal object ExtraScenePalettes {', '    val locations: Map<String, Map<String, Long>> = mapOf('];
for (const [loc, pal] of Object.entries(EXTRA_LOCPAL)) {
  pk.push(`        "${loc}" to mapOf(`);
  const pairs = Object.entries(pal).map(([k, v]) => `"${k}" to 0xFF${v.slice(1).toUpperCase()}`);
  for (let i = 0; i < pairs.length; i += 5) pk.push('            ' + pairs.slice(i, i + 5).join(', ') + ',');
  pk.push('        ),');
}
pk.push('    )', '}', '');
fs.writeFileSync(path.join(art, 'ExtraScenePalettes.kt'), pk.join('\n'));
