package com.example.violintuner.feature.journey.art

/** Colours of the places drawn after the handoff — generated by tools/journey/export.js from `EXTRA_LOCPAL` in extra-scenes.js: changed there, regenerated here. */
internal object ExtraScenePalettes {
    val locations: Map<String, Map<String, Long>> = mapOf(
        "prague" to mapOf(
            "stone" to 0xFFD8C39A, "stoneLit" to 0xFFE8D7B2, "stoneShade" to 0xFFB39B72, "stoneBase" to 0xFFC2AC82, "trim" to 0xFFF2ECD8,
            "roof" to 0xFF5E7A74, "roofLit" to 0xFF7C9A92, "dark" to 0xFF3A3040, "statue" to 0xFF8A8478,
        ),
        "leipzig" to mapOf(
            "plaster" to 0xFFEFE7D6, "plasterShade" to 0xFFD2C7B0, "roofTile" to 0xFF9A4B3A, "roofTileLit" to 0xFFB8614C, "roofTileShade" to 0xFF74372B,
            "copper" to 0xFF5E8F80, "copperLit" to 0xFF7FAF9F, "dark" to 0xFF3A3040, "stoneBase" to 0xFFB9AE98,
        ),
        "berlin" to mapOf(
            "ochre" to 0xFFD9A441, "ochreLit" to 0xFFECC062, "ochreShade" to 0xFFB07F2C, "ochreDark" to 0xFF8C6420, "glass" to 0xFF6F7F93,
            "concrete" to 0xFFCFC8BC, "concreteShade" to 0xFFABA498, "dark" to 0xFF3A3040,
        ),
        "amsterdam" to mapOf(
            "brick" to 0xFFA85C44, "brickLit" to 0xFFC0735A, "brickShade" to 0xFF82432F, "stone" to 0xFFEDE3CF, "stoneShade" to 0xFFCFC3AA,
            "roof" to 0xFF4E5560, "roofLit" to 0xFF6A727E, "gold" to 0xFFE2B74E, "dark" to 0xFF3A3040, "quay" to 0xFF6E5A4E,
            "quayLit" to 0xFF8A7466, "boat" to 0xFF3E5A4C, "boatLit" to 0xFFC9B48A,
        ),
        "paris" to mapOf(
            "stone" to 0xFFDCCDB0, "stoneLit" to 0xFFECDFC4, "stoneShade" to 0xFFB8A685, "stoneBase" to 0xFFC9B995, "trim" to 0xFFF3ECDA,
            "copper" to 0xFF5F9485, "copperLit" to 0xFF84B5A4, "gold" to 0xFFE2B74E, "dark" to 0xFF3A3040,
        ),
        "spb" to mapOf(
            "wall" to 0xFFDDB653, "wallLit" to 0xFFEBCB74, "wallShade" to 0xFFB3933F, "wallBase" to 0xFFC4A148, "trim" to 0xFFF6F1E4,
            "roof" to 0xFF7A8084, "roofLit" to 0xFF979DA1, "gold" to 0xFFE2B74E, "dark" to 0xFF3A3040,
        ),
        "moscow" to mapOf(
            "wall" to 0xFFEAD9A8, "wallLit" to 0xFFF5E8C2, "wallShade" to 0xFFC4B281, "wallBase" to 0xFFD3C293, "trim" to 0xFFF8F4EA,
            "roof" to 0xFF6F8278, "roofLit" to 0xFF8DA096, "bronze" to 0xFF3F4E47, "plinth" to 0xFF8F4A3C, "plinthLit" to 0xFFA96152,
            "dark" to 0xFF3A3040,
        ),
        "newyork" to mapOf(
            "brick" to 0xFFB5683C, "brickLit" to 0xFFCC7F50, "brickShade" to 0xFF8A4C2A, "trim" to 0xFFDDBB92, "marquee" to 0xFF2E2A38,
            "taxi" to 0xFFF2C230, "taxiShade" to 0xFFC99A16, "taxiDark" to 0xFF2A2430, "dark" to 0xFF3A3040,
        ),
        "buenosaires" to mapOf(
            "stone" to 0xFFE4D6BC, "stoneLit" to 0xFFF1E6CF, "stoneShade" to 0xFFBBAA8A, "stoneBase" to 0xFFCDBE9F, "trim" to 0xFFF7F1E2,
            "roof" to 0xFF7D6A5A, "roofLit" to 0xFF9A8675, "dark" to 0xFF3A3040,
        ),
        "tokyo" to mapOf(
            "tile" to 0xFFB9A48C, "tileLit" to 0xFFCDB9A0, "tileShade" to 0xFF8F7C66, "glass" to 0xFF6F8AA0, "steel" to 0xFF9AA3AD,
            "steelLit" to 0xFFBCC5CE, "steelShade" to 0xFF6E7781, "towerRed" to 0xFFD8452E, "towerWhite" to 0xFFF2EFE6, "blossom" to 0xFFF2B6C8,
            "blossomLit" to 0xFFFAD3DE, "blossomShade" to 0xFFD48BA4, "gold" to 0xFFE2B74E, "dark" to 0xFF3A3040,
        ),
    )
}
