// Exports the home of the violinist (spec 3.24) from the design handoff into the app.
//
//   node tools/home/export.js [previewDir]
//
// The handoff's catalogue is a runnable module (docs/design/project/home3/project/home-catalog.js):
// items, slots, houses and the function that composes a room. It is run here and written out as
//   app/src/main/assets/home/<house>.<eve|day>.scene              — the art: base, hero, every item in its place (and its framing on a shelf)
//   core/domain/home/HomeCatalogData.kt                            — what the rules need: prices, slots, cities
//   feature/home/art/HomeSilhouettes.kt, feature/home/HomeTexts.kt — silhouettes of the houses, ids → strings
//   res/values/home_catalog.xml                                    — names and descriptions
// Nothing of this is edited by hand: a thing is changed in the handoff and exported again.
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '../..');
global.window = {};
// the third handoff of the home (spec 3.29) is the second one's catalogue with the things redrawn: it is the one that is run
require(path.join(root, 'docs/design/project/home3/project/home-catalog.js'));
const C = window.buildHomeCatalog({ createElement: () => null });
const { ITEMS, SLOTS, SLOT, HOUSES, SIL, HP, HPD, L, hero, violin, pos, slotIn, bboxOf, compose, SPLASH_AWAY, SPLASH_HOME, ICONS } = C;

const CITY = { 'Кремона': 'cremona', 'Милан': 'milan', 'Зальцбург': 'salzburg', 'Вена': 'vienna', 'Прага': 'prague', 'Лейпциг': 'leipzig', 'Берлин': 'berlin', 'Амстердам': 'amsterdam', 'Париж': 'paris', 'Лондон': 'london', 'Санкт-Петербург': 'spb', 'Москва': 'moscow', 'Нью-Йорк': 'newyork', 'Буэнос-Айрес': 'buenosaires', 'Токио': 'tokyo', 'Сидней': 'sydney' };
const drawn = Object.values(HOUSES).filter(h => h.room);

// ---- art
const num = v => (v === undefined ? '' : String(v));
// a dashed stroke has no field of its own: it travels with the movements
const animOf = l => [l.anim, l.dash ? `dash:${String(l.dash).trim().split(/\s+/).join(':')}` : ''].filter(Boolean).join('+');
const line = l => [l.fill, l.depth, num(l.op), num(l.tx), num(l.ty), num(l.sc), l.glow ? 1 : '', l.stroke || '', num(l.sw), l.fillNone ? 1 : '', l.d, animOf(l)].join('\t');
// birds past the window, as in the room the journey began with: they belong to the view, whatever it is
const BIRD = (x, y, s, left, span) => L('bird', `M${x - 5 * s} ${y}Q${x - 2.5 * s} ${y - 3 * s} ${x} ${y}Q${x + 2.5 * s} ${y - 3 * s} ${x + 5 * s} ${y}Q${x + 2.5 * s} ${y - 1.3 * s} ${x} ${y + 1 * s}Q${x - 2.5 * s} ${y - 1.3 * s} ${x - 5 * s} ${y}Z`, 1, { anim: `bird:${left}:${span}` });
const birds = (x, y) => [[-30, -33, 1.05], [-16, -24, 1.3], [8, -38, .9], [20, -18, 1.15], [40, -30, 1]].map(([dx, dy, k]) => BIRD(x + dx, y + dy, k, x - 48, 96));

// life outside (owner, after 0.51): a flock over the roofs and a car that passes — in the street before the rented room,
// on the far road behind the garden of the wooden house (the grass hides its wheels). All layers of the car ride as one.
const flockOut = spots => spots.map(([x, y, k]) => ({ ...BIRD(x, y, k * 1.3, -30, 472), depth: 1 }));
const passing = (x, y, k, c, eve, depth) => [
  L('rgba(20,16,30,.28)', `M${x} ${y + 1 * k}h${52 * k}v${3 * k}h${-52 * k}Z`, depth),
  L(c.body, `M${x} ${y - 12 * k}h${52 * k}v${12 * k}h${-52 * k}Z`, depth), L(c.body, `M${x + 12 * k} ${y - 12 * k}l${5 * k} ${-9 * k}h${20 * k}l${5 * k} ${9 * k}Z`, depth),
  L(eve ? 'window' : c.dark, `M${x + 16 * k} ${y - 13 * k}l${3 * k} ${-6 * k}h${16 * k}l${3 * k} ${6 * k}Z`, depth),
  L(c.dark, `M${x + 6 * k} ${y}a${4 * k} ${4 * k} 0 1 0 ${8 * k} 0a${4 * k} ${4 * k} 0 1 0 ${-8 * k} 0Z`, depth), L(c.dark, `M${x + 38 * k} ${y}a${4 * k} ${4 * k} 0 1 0 ${8 * k} 0a${4 * k} ${4 * k} 0 1 0 ${-8 * k} 0Z`, depth),
  L('window', `M${x + 49 * k} ${y - 9 * k}h${3 * k}v${3 * k}h${-3 * k}Z`, depth),
];
const riding = (layers, speed, x0, x1, pause) => layers.map(l => ({ ...l, anim: `ride:${speed}:${-(x1 + 24)}:${412 - x0 + 24 + pause}` }));
const OUT_LIFE = {
  rent: (layers, eve) => [...layers.slice(0, 2), ...flockOut([[70, 72, 1], [88, 84, .8], [330, 58, .9], [348, 70, .7]]), ...layers.slice(2), ...riding(passing(40, 232, 1.15, { body: '#3F6FA8', dark: '#23202B' }, eve, 2), 34, 40, 100, 260)],
  wood: (layers, eve) => { const at = layers.findIndex(l => l.fill === 'foliageShade'); return [...layers.slice(0, 2), ...flockOut([[60, 78, 1], [80, 90, .8], [96, 70, .7], [350, 62, .9]]), ...layers.slice(2, at), ...riding(passing(20, 191, .5, { body: '#B5483C', dark: '#23202B' }, eve, 1), 9, 20, 46, 140), ...layers.slice(at)]; },
};

const out = path.join(root, 'app/src/main/assets/home');
fs.rmSync(out, { recursive: true, force: true });
fs.mkdirSync(out, { recursive: true });
const MARK = { pat: '@pat', floor: '@floorpat', curtain: '@curtain' };
for (const H of drawn) {
  for (const eve of [true, false]) {
    const lines = ['# generated by tools/home/export.js: do not edit by hand', `house=${H.id}`];
    const withPat = H.room(eve, () => [L(MARK.pat, 'M0 0Z')], () => [L(MARK.floor, 'M0 0Z')]);
    lines.push('@room', ...withPat.map(line));
    // the floor's own lines, when no floor with a pattern is laid
    const plain = H.room(eve, null, null), marked = H.room(eve, null, () => [L(MARK.floor, 'M0 0Z')]);
    const at = marked.findIndex(l => l.fill === MARK.floor);
    lines.push('@floorpat default', ...plain.slice(at, at + plain.length - marked.length + 1).map(line));
    lines.push('@out', ...(OUT_LIFE[H.id] ? OUT_LIFE[H.id](H.outside(eve, MARK.curtain), eve) : H.outside(eve, MARK.curtain)).map(line));
    lines.push('@hero', ...hero(H.hero[0], H.hero[1], .95, 1).map(line));
    for (const it of ITEMS) {
      if (it.pat) lines.push(`@${it.s === 'floor' ? 'floorpat' : 'pat'} ${it.id}`, ...it.pat(eve).map(line));
      if (!it.L || !slotIn(it.s, H.id)) continue;
      const p = pos(H.id, it);
      // a window is its backing, then the view, then the glazing bars: the backing is a section of its own
      if (it.L0) lines.push(`@back ${it.id}`, ...it.L0(p.x, p.y, eve).map(line));
      // no violin yet — the student's one lies in the open case: the present of the shop «leaves its case» literally
      if (it.s === 'case') lines.push(`@caseviolin ${it.id}`, ...violin(p.x + 3, p.y - 12, .55, { body: 'varnishRaw' }).map(line));
      const layers = [...it.L(p.x, p.y, eve), ...(it.s === 'view' ? birds(p.x, p.y) : [])];
      const b = bboxOf(layers);
      // a thing whose own box would make it a dot on a shelf (the chandelier on its long rod) brings the box it is framed by there
      const shelf = it.tb ? [p.x + it.tb[0], p.y + it.tb[1], p.x + it.tb[2], p.y + it.tb[3]] : [];
      lines.push(`@item ${it.id} ${[...b, ...shelf].map(v => Math.round(v * 10) / 10).join(' ')}`, ...layers.map(line));
      if (it.id.startsWith('cat_') && slotIn('oPorch', H.id)) { const q = pos(H.id, { s: 'oPorch' }); lines.push(`@porch ${it.id}`, ...it.L(q.x, q.y, eve).map(line)); }
    }
    fs.writeFileSync(path.join(out, `${H.id}.${eve ? 'eve' : 'day'}.scene`), lines.join('\n') + '\n');
  }
}

// ---- what the rules need
const kt = s => JSON.stringify(s).replace(/\$/g, '\\$');
const hex = c => `0xFF${c.slice(1).toUpperCase()}`;
const pal = o => (o ? `mapOf(${Object.entries(o).map(([k, v]) => `${kt(k)} to ${hex(v)}`).join(', ')})` : 'emptyMap()');
const GROUP = { instr: 'INSTRUMENT', music: 'MUSIC', room: 'ROOM', light: 'LIGHT', furn: 'FURNITURE', plant: 'PLANT', life: 'LIFE', pet: 'PET', out: 'OUTSIDE' };
const data = ['package com.violinjourney.app.core.domain.home', '', '/** The catalogue of the home — generated by tools/home/export.js from the design handoff `home-catalog.js`: changed there, regenerated here. */', 'object HomeCatalogData {', '    val items: List<HomeItem> = listOf('];
for (const it of ITEMS) {
  if (it.from && !CITY[it.from]) throw new Error(`a city the route does not know: ${it.from}`);
  data.push(`        HomeItem(${kt(it.id)}, HomeGroup.${GROUP[it.g]}, slot = ${kt(it.s)}, at = ${it.at ? kt(it.at) : 'null'}, price = ${it.p}, from = ${it.from ? kt(CITY[it.from]) : 'null'}, z = ${it.z ?? 1}, outside = ${!!it.out}, drawn = ${!!it.L}, pattern = ${!!it.pat}, palette = ${pal(it.over)}),`);
}
data.push('    )', '', '    val slots: List<HomeSlot> = listOf(');
for (const s of SLOTS) data.push(`        HomeSlot(${kt(s.id)}, outside = ${!!s.out}, palette = ${!!s.pal}, houses = ${s.rooms ? `setOf(${s.rooms.map(kt).join(', ')})` : 'null'}),`);
data.push('    )', '', '    val houses: List<HomeHouse> = listOf(');
for (const h of Object.values(HOUSES)) data.push(`        HomeHouse(${kt(h.id)}, price = ${h.price}, drawn = ${!!h.room}),`);
data.push('    )', '', '    /** Tokens of the room (handoff `HP`) and what the day changes in them (`HPD`). */', `    val tokens: Map<String, Long> = ${pal(HP)}`, `    val dayTokens: Map<String, Long> = ${pal(HPD)}`, '}', '');
fs.writeFileSync(path.join(root, 'shared/src/commonMain/kotlin/com/violinjourney/app/core/domain/home/HomeCatalogData.kt'), data.join('\n'));

// ---- words
const xml = s => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/'/g, "\\'").replace(/"/g, '\\"');
const res = ['<?xml version="1.0" encoding="utf-8"?>', '<!-- generated by tools/home/export.js from the design handoff: do not edit by hand -->', '<resources>'];
const texts = ['package com.violinjourney.app.feature.home', '', 'import com.violinjourney.app.R', '', '/** Ids of the catalogue → their words — generated by tools/home/export.js. */', 'internal object HomeTexts {', '    val itemNames: Map<String, Int> = mapOf('];
const str = (name, text) => res.push(`    <string name="${name}" formatted="false">${xml(text)}</string>`);
ITEMS.forEach(it => { str(`home_item_${it.id}`, it.n); texts.push(`        ${kt(it.id)} to R.string.home_item_${it.id},`); });
texts.push('    )', '    val itemNotes: Map<String, Int> = mapOf(');
ITEMS.forEach(it => { str(`home_item_${it.id}_note`, it.d || ''); texts.push(`        ${kt(it.id)} to R.string.home_item_${it.id}_note,`); });
texts.push('    )', '    val slotNames: Map<String, Int> = mapOf(');
SLOTS.forEach(s => { str(`home_slot_${s.id}`, s.name); texts.push(`        ${kt(s.id)} to R.string.home_slot_${s.id},`); });
texts.push('    )', '    val houseNames: Map<String, Int> = mapOf(');
Object.values(HOUSES).forEach(h => { str(`home_house_${h.id}`, h.name); texts.push(`        ${kt(h.id)} to R.string.home_house_${h.id},`); });
texts.push('    )', '    val houseNotes: Map<String, Int> = mapOf(');
Object.values(HOUSES).forEach(h => { str(`home_house_${h.id}_note`, h.sub); texts.push(`        ${kt(h.id)} to R.string.home_house_${h.id}_note,`); });
texts.push('    )', '    val houseNews: Map<String, Int> = mapOf(');
Object.values(HOUSES).forEach(h => { res.push(`    <string-array name="home_house_${h.id}_news">`, ...(h.news || []).map(n => `        <item>${xml(n)}</item>`), '    </string-array>'); texts.push(`        ${kt(h.id)} to R.array.home_house_${h.id}_news,`); });
texts.push('    )', '}', '');
res.push('</resources>', '');
fs.writeFileSync(path.join(root, 'app/src/main/res/values-ru/home_catalog.xml'), res.join('\n'));
fs.mkdirSync(path.join(root, 'app/src/main/java/com/violinjourney/app/feature/home/art'), { recursive: true });
fs.writeFileSync(path.join(root, 'app/src/main/java/com/violinjourney/app/feature/home/HomeTexts.kt'), texts.join('\n'));
const sil = ['package com.violinjourney.app.feature.home.art', '', '/** Silhouettes of the houses (grid 200 × 120) — generated by tools/home/export.js from the handoff\'s `SIL`. */', 'object HomeSilhouettes {', '    val paths: Map<String, List<String>> = mapOf('];
for (const [k, v] of Object.entries(SIL)) sil.push(`        ${kt(k)} to listOf(${v.map(kt).join(', ')}),`);
sil.push('    )', '}', '');
fs.writeFileSync(path.join(root, 'shared/src/commonMain/kotlin/com/violinjourney/app/feature/home/art/HomeSilhouettes.kt'), sil.join('\n'));

// ---- preview: the rooms the handoff composes, to compare the app against
const previewDir = process.argv[2];
if (previewDir) {
  fs.mkdirSync(previewDir, { recursive: true });
  const svg = (layers, palette) => { const col = t => (t.startsWith('#') || t.startsWith('rgba') ? t : palette[t] ?? (t === 'none' ? 'none' : 'magenta')); const stop = (o, c) => { const m = c.match(/rgba\((\d+),(\d+),(\d+),([\d.]+)\)/); return m ? `<stop offset="${o}" stop-color="rgb(${m[1]},${m[2]},${m[3]})" stop-opacity="${m[4]}"/>` : `<stop offset="${o}" stop-color="${c}"/>`; }; return `<svg xmlns="http://www.w3.org/2000/svg" width="824" height="520" viewBox="0 0 412 260"><defs><linearGradient id="s" x1="0" y1="0" x2="0" y2="1">${stop(0, palette.sky)}${stop(1, palette.skyLow)}</linearGradient><radialGradient id="g">${stop(0, palette.glow)}${stop(1, 'rgba(255,196,110,0)')}</radialGradient></defs>${layers.map(l => `<path d="${l.d}" fill="${l.fillNone ? 'none' : l.fill === 'SKY' ? 'url(#s)' : l.fill === 'GLOW' ? 'url(#g)' : col(l.fill)}"${l.op !== undefined ? ` opacity="${l.op}"` : ''}${l.stroke ? ` stroke="${col(l.stroke)}" stroke-width="${l.sw}"` : ''}/>`).join('')}</svg>`; };
  for (const H of drawn) for (const mode of ['eve', 'day']) for (const outside of [false, true]) {
    const all = ITEMS.map(i => i.id);
    const r = compose(H.id, mode, all, { outside });
    fs.writeFileSync(path.join(previewDir, `${H.id}.${outside ? 'out' : 'room'}.${mode}.svg`), svg(r.l, C.palOf(mode, r.over)));
  }
}
// ---- the title cards between the home and the journey (handoff 28d): plain scenes, read like postcards
for (const eve of [true, false]) {
  const mode = eve ? 'eve' : 'day';
  const head = aerial => ['# generated by tools/home/export.js: do not edit by hand', `loc=house;aerial=${aerial}`];
  // the handoff's sky ends at the horizon (y 190) and its skyline begins lower: on a page that gap is the page, on a phone it is a dark band — the low sky goes on under it
  const away = SPLASH_AWAY(eve, 0, { fly: true });
  const sky = away.findIndex(l => l.fill === 'SKY');
  away.splice(sky + 1, 0, L('skyLow', 'M-600 190h1600v80h-1600Z', 0));
  // upright the card stands in the middle of the screen: the land goes on down under the caption
  away.splice(away.findIndex(l => l.fill === 'farLit') + 1, 0, L('farLit', 'M-600 259h1600v1200h-1600Z', 0));
  fs.writeFileSync(path.join(out, `splash.away.${mode}.scene`), [...head(1), ...away.map(line)].join('\n') + '\n');
  fs.writeFileSync(path.join(out, `splash.home.${mode}.scene`), [...head(0), ...SPLASH_HOME(eve).map(line)].join('\n') + '\n');
}
console.log('icons to carry into IconPaths by hand:', ICONS.map(i => `${i.name}: ${JSON.stringify(i.paths)}`).join('\n  '));
console.log(`${ITEMS.length} items, ${SLOTS.length} slots, ${drawn.length} houses drawn of ${Object.keys(HOUSES).length}`);
